// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReconnectToken } from "./ReconnectToken";
import type { RoomId } from "./RoomId";

export type ClientMessage = { type: "join_room", username: string, room: RoomId | null, } | { type: "rejoin_room", token: ReconnectToken, room: RoomId, } | { type: "update_config", config: any, } | { type: "start_game" } | { type: "do_action", action: any, } | { type: "game_view_request" };